name: Build Freenet Website

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Site
        id: cache-site
        uses: actions/cache@v4
        with:
          path: site
          key: ipfs-test-site

      - name: Checkout repository
        if: steps.cache-site.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          persist-credentials: "false"

      - name: Python setup
        if: steps.cache-site.outputs.cache-hit != 'true'
        uses: actions/setup-python@v5

      - name: Install Python dependencies
        if: steps.cache-site.outputs.cache-hit != 'true'
        run: |
          pip install mkdocs-material
          sudo apt install pngquant

      - name: Build website
        if: steps.cache-site.outputs.cache-hit != 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARDS: false
        run: |
          mkdocs build --config-file config/mkdocs-offline.yml
          mkdocs --version

      - name: Save Site
        if: steps.cache-site.outputs.cache-hit != 'true'
        id: cache-site-save
        uses: actions/cache/save@v4
        with:
          path: site
          key: ipfs-test-site

      - run: |
          touch site/test-file.txt
          tar -czvf site-offline-test.tar.gz site

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-offline-test.tar.gz
          path: site-offline-test.tar.gz

  deploy:
    uses: privacyguides/webserver/.github/workflows/deploy-hyphanet.yml@main
    needs: build
    with:
      environment: dweb
      netpath: test10582
      public_key: ${{ vars.HYPHANET_PUBLIC_KEY }}
    secrets:
      private_key: ${{ secrets.HYPHANET_PRIVATE_KEY }}
